name: codeception-poc
type: php
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.4"
omit_containers: ["dba", "db"]
use_dns_when_possible: false
composer_version: "2"
web_environment: []